### ISSUE TITLE
GIF walkthrough

### ISSUE THREAD

**Issue by abassie** [StChabnah/Group-Project#14]
Here is a GIF showing the progress we have made building PocketPantry. @codepathreview
![app](https://cloud.githubusercontent.com/assets/16269214/14094500/88b0be96-f51c-11e5-96fa-74628a8ce3d4.gif)

**Comment by avo1** [comment]
:+1: Great job on the first implementation sprint! The app is really starting to come together. There are 2 weeks left to complete all of the required stories so that you have an MVP (minimum viable product). The purpose of this is to get the minimum set of functionality implemented first and then focus on adding in optionals afterwards. This ensures you have all the basics in place before adding in the additionals and polish.
